SRC=src/options.c src/parse.c src/parse_var.c src/parse_rule.c src/execute_node.c src/tools.c src/main.c
OBJ=src/options.o src/parse.o src/parse_var.o src/parse_rule.o src/execute_node.o src/tools.o src/main.o

all: $(OBJ)
	gcc -o minimake $(OBJ)

$(OBJ): $(SRC)
	gcc -c $(SRC)



